### ISSUE TITLE
Sort out automatic code formatting

### ISSUE THREAD

**Issue by kpet** [kpet/clvk#1]
So we don't spend time arguing about braces and spaces in code reviews.
* Document process
* Put a bot in place to check changes

**Comment by kpet** [comment]
That is exactly my plan :). Thanks for the tip, I'll have a look at how it's done there.

**Comment by jrprice** [comment]
+1 to this - I have some more substantial contributions on the way and it'd be great to get this in place. I can volunteer to do the scripting/Travis CI work if it helps?

@kpet (assuming the answer to the above is "yes"):
Would you want me to try and .set up a `.clang-format` that matches the current style as closely as possible, or would you rather just pick one of the off-the-shelf configs?

**Comment by kpet** [comment]
I've now got a `.clang-format` I'm happy enough with and a change that reformats the entire code base ready. There are still a few weird things here and there but nothing that makes it worth delaying. Travis allowing, I should have that merged before you start on Monday.

Many thanks! I would definitely appreciate some help with the scripting and Travis aspect of it though :). What I had in mind was to have a single shell or python script that knows what folders need formatting and can return status for the CI but I'm open to suggestions.

**Comment by jrprice** [comment]
> What I had in mind was to have a single shell or python script that knows what folders need formatting and can return status for the CI but I'm open to suggestions.

Sounds reasonable. With `git-clang-format` you can filter by extension and also limit formatting checks to code that has changed in the PR in question (which can sometimes be useful), with a command like this:

    git-clang-format --diff origin/master --extensions cc,hh

Then it's just a case of grepping the output of this command to check for formatting violations.

**Comment by kpet** [comment]
I don't think I've used `git-clang-format` before but it sounds like a good idea.

**Comment by kpet** [comment]
This is now done and documented in the contribution guide. @jrprice Thanks again for the help :).
