### ISSUE TITLE
Correctly perform image layout transitions

### ISSUE THREAD

**Issue by kpet** [kpet/clvk#108]
Things work on nVidia's driver without them but this is definitely incorrect.

**Comment by alan-baker** [comment]
Do you have thoughts about how you want to go about this? I believe I'm running into this issue currently with some Mace unit tests. I'm planning to investigate some ways to make sure this happens, but wanted to check if you have this planned yet.

**Comment by kpet** [comment]
I've got a couple of prototypes already but nothing I'm really satisfied with. Implementing this in a way that's fast and simple for the common cases and still correct for the more exotic ones is surprisingly tricky. Since I haven't found a single case where this was needed to get correct results with the drivers I'm testing on, I haven't prioritised this much.

If possible with your unit test, I suggest you just hack clvk to add a transition to the first command buffer that uses the image. This should be straightforward to do and may allow you to confirm whether the lack of correct layout transition is the source of your problem. I suggest enabling the validation layers when working on this. If it turns out this is the source of your problem, I'm happy to either bump that up my list or provide more detailed advice.

**Comment by alan-baker** [comment]
#151 fixed my problem, so we can defer this while we come up with a good solution.
