### ISSUE TITLE
Support CL_MEM_OBJECT_IMAGE1D_BUFFER images

### ISSUE THREAD

**Issue by kpet** [kpet/clvk#122]

**Comment by aarongreig** [comment]
I was looking at doing this with VkBufferView but then I noticed you've got a ticket assigned for it, have you started working on this or should I keep going?

**Comment by kpet** [comment]
I've got a set of changes (clspv+clvk+CTS) in progress. I still have a couple of commands to support and bugs to chase. If you're in a rush I can hand over to you. Let me know.

**Comment by aarongreig** [comment]
Cool, no rush just eager to avoid duplicate effort.
