### ISSUE TITLE
Clvk should add --std430-ubo-layout if VK_KHR_uniform_buffer_standard_layout is supported

### ISSUE THREAD

**Issue by alan-baker** [kpet/clvk#143]
Looser layout restrictions could be supported automatically by detecting support for the extension. I would still leave conversion to UBO to the discretion of the user.

**Comment by kpet** [comment]
Yes, we did discuss this and I'd made a note of it but hadn't got around to implementing this yet. Do you guys have a patch? (Just checking do I don't duplicate work.)

**Comment by alan-baker** [comment]
No, not currently. Just wanted to write it down so I don't forget again.
