### ISSUE TITLE
Descriptor pool prohibits same kernel from being enqueued multiple times

### ISSUE THREAD

**Issue by jrprice** [kpet/clvk#153]
The descriptor pool creation in `cvk_kernel::init()` provides space for exactly the number of descriptors required by one instance of the kernel. Descriptors sets are allocated when a kernel is enqueued and are only freed when that kernel instance finishes executing. This means that the descriptor pool cannot support a single kernel having multiple enqueued instances in flight at once. I'm receiving `VK_ERROR_OUT_OF_POOL_MEMORY ` from `vkAllocateDescriptorSets` with certain drivers when this happens.

The simplest fix I can see would be to have a separate descriptor pool for each kernel instance (i.e. stored in `cvk_command_kernel`, created in `cvk_command_kernel::build()` and destroyed by `~cvk_command_kernel()`). This may negatively impact the speed of `clEnqueueNDRangeKernel` if descriptor pool creation is slow (is it?).

An alternative would be to allow some specific number of simultaneous kernel instances in flight by multiplying the descriptor counts used during pool creation by some constant value. This would mean we'd need to track how many instances were in flight and block during enqueue if we hit this limit, which seems undesirable (though we could potentially move this part of kernel submission to a background thread). There's also an issue with descriptor pool fragmentation - even when descriptor sets are freed we may still have issues allocating more.

Due to the fragmentation issue I'm leaning towards implementing the former approach (one pool per kernel instance). Does this sound acceptable for now, or do you have a better suggestion?

**Comment by kpet** [comment]
I've fixed that a long time ago but managed to regress on it in a very silly way as part of https://github.com/kpet/clvk/commit/58e0c9af8a0f70b454e04cbc95bcfefbc93666f1. One descriptor pool per instance really isn't an option. I did go for the hard-coded limit on the number of kernels in flight (`cvk_kernel::MAX_INSTANCES`). I've pushed https://github.com/kpet/clvk/commit/689c2a31813cdcec87624acd9376906c2213f13f as a quick fix of the regression.

I suggest we keep this ticket open to cover the following improvements:
- Account for the exact number of descriptor sets per instance. It's currently not a practical issue unless you need more than half of `cvk_kernel::MAX_INSTANCES` but the code is wrong.
- Add a test to exercise many instances in flight.

One last note: it seems some drivers wongly multiply the pool sizes given at descriptor pool creation time by the max number of sets requested (i.e. they assume `pPoolSizes`is given per descriptor set). That's probably the reason I didn't spot the regression with my routine testing.
