### ISSUE TITLE
clspv fails on Ubuntu 18.04

### ISSUE THREAD

**Issue by tingxingdong** [kpet/clvk#191]
After I run ubuntu I see a clsvp error:

./simple_test_static 
Platform: clvk
Device: Radeon RX 5500 XT
clspv: Unknown command line argument '-max-pushconstant-size=128'.  Try: '/home/tim/clvk/build/clspv --help'
clspv: Did you mean '--max-heap-to-stack-size=128'?
/home/tim/clvk/tests/simple/simple.cpp:76 error after CL call: -11

**Comment by kpet** [comment]
Most likely your clspv binary is out of date. Did you forget to update submodules and dependencies  after updating clvk (see https://github.com/kpet/clvk#getting-dependencies)?

**Comment by tingxingdong** [comment]
Thanks, after I updated it. It passed. 
Another issue is: does the timing function "clGetEventProfilingInfo" work correctly? If on AMD OCL driver, the timing is around 20x faster. However, they both return quickly. So I guess it is just the event timing function issue, not because the wall time is really 20x slower. 

clEnqueueNDRangeKernel: (16x16)-(16x16)!
Profiling(1): 395755.000000 ns

**Comment by kpet** [comment]
This is expected. You may want to try using `CLVK_QUEUE_PROFILING_USE_TIMESTAMP_QUERIES` (see README). #110 will fix that if your driver supports VK_EXT_calibrated_timestamps.

**Comment by tingxingdong** [comment]
Another issue is: does the timing function "clGetEventProfilingInfo" work correctly? If on AMD OCL driver, the timing is around 20x faster. However, they both return quickly. So I guess it is just the event timing function issue, not because the wall time is really 20x slower.

**Comment by tingxingdong** [comment]
> Another issue is: does the timing function "clGetEventProfilingInfo" work correctly? If on AMD OCL driver, the timing is around 20x faster. However, they both return quickly. So I guess it is just the event timing function issue, not because the wall time is really 20x slower.

I fixed this bug. It is my fault I did not enable profiling when createCommandQuque.
