### ISSUE TITLE
Does half<->float conversion supported on clvk?

### ISSUE THREAD

**Issue by tingxingdong** [kpet/clvk#239]
OpenCL provide vstore_half primitive to do the conversion.  (see https://man.opencl.org/vstore_half.html).
However,  there is a compilation error on clvk. No compilation error on AMD driver. 

error: 114: OpLoad Pointer <id> '82[%82]' is not a logical pointer.
  %83 = OpLoad %uint %82

If this primitive is not supported? Any other method? thanks

**Comment by kpet** [comment]
This should work. I can't reproduce the issue. Would you have a sample kernel please?

**Comment by tingxingdong** [comment]
It just 1 line of code. u can insert it in any test code. 

`float fl = 1.0; half ha; vstore_half(fl, 0, &ha);`

**Comment by kpet** [comment]
Hmm, still can't reproduce it. Would you have a full kernel that has the issue please? Any specific compilation options in the application?

**Comment by tingxingdong** [comment]
With the default compilation option. NULL. I walked around the problem by use ‘convert_half’ primitive

**Comment by tingxingdong** [comment]
Does clvk support building/running a program with 3 kernels in the same file?  (and then launch 3 kernel one by one in main.cpp). Running it gives me segment fault immediately.  Building / run 1 kernel program is fine.
