### ISSUE TITLE
Multiple build issues on Windows using MSVC

### ISSUE THREAD

**Issue by kpet** [kpet/clvk#26]
See https://github.com/kpet/clvk/pull/25

**Comment by kpet** [comment]
Needs https://github.com/google/clspv/issues/212 to be resolved.

**Comment by kpet** [comment]
@rszymanski I've updated clspv and your fixes should be there. Could you retest and close the issue if it works please?

**Comment by rszymanski** [comment]
There are new errors now in clspv\lib\SPIRVProducerPass.cpp. This file has enabled treating warnings as errors so don't see point in fixing anything there, if the main developers are not using msvc. This will break soon anyway.
