### ISSUE TITLE
simple_test results are all 0s but log looks good. 

### ISSUE THREAD

**Issue by tingxingdong** [kpet/clvk#263]
export CLVK_LOG=3
----------------------------------------------------

[CLVK] Starting initialisation
[CLVK] 6 layers visible
[CLVK]   VK_LAYER_LUNARG_api_dump, spec version 1.2.148, impl version 2
[CLVK]   VK_LAYER_LUNARG_screenshot, spec version 1.2.148, impl version 1
[CLVK]   VK_LAYER_LUNARG_gfxreconstruct, spec version 1.2.148, impl version 36866
[CLVK]   VK_LAYER_KHRONOS_validation, spec version 1.2.148, impl version 1
[CLVK]   VK_LAYER_LUNARG_device_simulation, spec version 1.2.148, impl version 1
[CLVK]   VK_LAYER_LUNARG_monitor, spec version 1.2.148, impl version 1
[CLVK] 17 extensions are supported
[CLVK]   VK_KHR_device_group_creation, spec version 1
[CLVK]   VK_KHR_display, spec version 23
[CLVK]   VK_KHR_external_fence_capabilities, spec version 1
[CLVK]   VK_KHR_external_memory_capabilities, spec version 1
[CLVK]   VK_KHR_external_semaphore_capabilities, spec version 1
[CLVK]   VK_KHR_get_display_properties2, spec version 1
[CLVK]   VK_KHR_get_physical_device_properties2, spec version 2
[CLVK]   VK_KHR_get_surface_capabilities2, spec version 1
[CLVK]   VK_KHR_surface, spec version 25
[CLVK]   VK_KHR_wayland_surface, spec version 6
[CLVK]   VK_KHR_xcb_surface, spec version 6
[CLVK]   VK_KHR_xlib_surface, spec version 6
[CLVK]   VK_EXT_acquire_xlib_display, spec version 1
[CLVK]   VK_EXT_debug_report, spec version 9
[CLVK]   VK_EXT_debug_utils, spec version 2
[CLVK]   VK_EXT_direct_mode_display, spec version 1
[CLVK]   VK_EXT_display_surface_counter, spec version 1
[CLVK] Created the VkInstance
[CLVK] Found 1 physical devices
[CLVK] Initialising device Radeon RX 5500
[CLVK]   API Version: 1.2.145
[CLVK] Physical device (Integrated GPU) has 2 queue families:
[CLVK]   queue family 0:  2 queues | GRAPHICS COMPUTE TRANSFER SPARSE_BINDING
[CLVK]   queue family 1:  4 queues | COMPUTE TRANSFER SPARSE_BINDING
[CLVK] 94 extensions are supported
[CLVK]   VK_KHR_16bit_storage, spec version 1
[CLVK]     ENABLING
[CLVK]   VK_KHR_8bit_storage, spec version 1
[CLVK]     ENABLING
[CLVK]   VK_KHR_bind_memory2, spec version 1
[CLVK]   VK_KHR_create_renderpass2, spec version 1
[CLVK]   VK_KHR_dedicated_allocation, spec version 3
[CLVK]   VK_KHR_depth_stencil_resolve, spec version 1
[CLVK]   VK_KHR_descriptor_update_template, spec version 1
[CLVK]   VK_KHR_device_group, spec version 4
[CLVK]   VK_KHR_draw_indirect_count, spec version 1
[CLVK]   VK_KHR_driver_properties, spec version 1
[CLVK]     ENABLING
[CLVK]   VK_KHR_external_fence, spec version 1
[CLVK]   VK_KHR_external_fence_fd, spec version 1
[CLVK]   VK_KHR_external_memory, spec version 1
[CLVK]   VK_KHR_external_memory_fd, spec version 1
[CLVK]   VK_KHR_external_semaphore, spec version 1
[CLVK]   VK_KHR_external_semaphore_fd, spec version 1
[CLVK]   VK_KHR_get_memory_requirements2, spec version 1
[CLVK]   VK_KHR_imageless_framebuffer, spec version 1
[CLVK]   VK_KHR_image_format_list, spec version 1
[CLVK]   VK_KHR_maintenance1, spec version 2
[CLVK]   VK_KHR_maintenance2, spec version 1
[CLVK]   VK_KHR_maintenance3, spec version 1
[CLVK]   VK_KHR_multiview, spec version 1
[CLVK]   VK_KHR_pipeline_executable_properties, spec version 1
[CLVK]   VK_KHR_relaxed_block_layout, spec version 1
[CLVK]   VK_KHR_sampler_mirror_clamp_to_edge, spec version 3
[CLVK]   VK_KHR_separate_depth_stencil_layouts, spec version 1
[CLVK]   VK_KHR_shader_atomic_int64, spec version 1
[CLVK]   VK_KHR_shader_clock, spec version 1
[CLVK]   VK_KHR_shader_draw_parameters, spec version 1
[CLVK]   VK_KHR_shader_float16_int8, spec version 1
[CLVK]     ENABLING
[CLVK]   VK_KHR_shader_float_controls, spec version 4
[CLVK]   VK_KHR_shader_non_semantic_info, spec version 1
[CLVK]   VK_KHR_shader_subgroup_extended_types, spec version 1
[CLVK]   VK_KHR_spirv_1_4, spec version 1
[CLVK]   VK_KHR_storage_buffer_storage_class, spec version 1
[CLVK]   VK_KHR_swapchain, spec version 70
[CLVK]   VK_KHR_swapchain_mutable_format, spec version 1
[CLVK]   VK_KHR_uniform_buffer_standard_layout, spec version 1
[CLVK]     ENABLING
[CLVK]   VK_KHR_variable_pointers, spec version 1
[CLVK]     ENABLING
[CLVK]   VK_KHR_vulkan_memory_model, spec version 3
[CLVK]   VK_EXT_calibrated_timestamps, spec version 1
[CLVK]     ENABLING
[CLVK]   VK_EXT_conditional_rendering, spec version 2
[CLVK]   VK_EXT_conservative_rasterization, spec version 1
[CLVK]   VK_EXT_depth_clip_enable, spec version 1
[CLVK]   VK_EXT_depth_range_unrestricted, spec version 1
[CLVK]   VK_EXT_descriptor_indexing, spec version 2
[CLVK]   VK_EXT_extended_dynamic_state, spec version 1
[CLVK]   VK_EXT_external_memory_host, spec version 1
[CLVK]   VK_EXT_global_priority, spec version 2
[CLVK]   VK_EXT_hdr_metadata, spec version 2
[CLVK]   VK_EXT_host_query_reset, spec version 1
[CLVK]   VK_EXT_inline_uniform_block, spec version 1
[CLVK]   VK_EXT_line_rasterization, spec version 1
[CLVK]   VK_EXT_memory_budget, spec version 1
[CLVK]   VK_EXT_memory_priority, spec version 1
[CLVK]   VK_EXT_pci_bus_info, spec version 2
[CLVK]   VK_EXT_pipeline_creation_cache_control, spec version 3
[CLVK]   VK_EXT_pipeline_creation_feedback, spec version 1
[CLVK]   VK_EXT_post_depth_coverage, spec version 1
[CLVK]   VK_EXT_queue_family_foreign, spec version 1
[CLVK]   VK_EXT_sample_locations, spec version 1
[CLVK]   VK_EXT_scalar_block_layout, spec version 1
[CLVK]   VK_EXT_separate_stencil_usage, spec version 1
[CLVK]   VK_EXT_shader_demote_to_helper_invocation, spec version 1
[CLVK]   VK_EXT_shader_stencil_export, spec version 1
[CLVK]   VK_EXT_shader_subgroup_ballot, spec version 1
[CLVK]   VK_EXT_shader_subgroup_vote, spec version 1
[CLVK]   VK_EXT_shader_viewport_index_layer, spec version 1
[CLVK]   VK_EXT_subgroup_size_control, spec version 2
[CLVK]   VK_EXT_texel_buffer_alignment, spec version 1
[CLVK]   VK_EXT_transform_feedback, spec version 1
[CLVK]   VK_EXT_vertex_attribute_divisor, spec version 3
[CLVK]   VK_AMD_buffer_marker, spec version 1
[CLVK]   VK_AMD_device_coherent_memory, spec version 1
[CLVK]   VK_AMD_draw_indirect_count, spec version 2
[CLVK]   VK_AMD_gcn_shader, spec version 1
[CLVK]   VK_AMD_gpa_interface, spec version 1
[CLVK]   VK_AMD_gpu_shader_half_float, spec version 2
[CLVK]   VK_AMD_gpu_shader_int16, spec version 2
[CLVK]   VK_AMD_memory_overallocation_behavior, spec version 1
[CLVK]   VK_AMD_negative_viewport_height, spec version 1
[CLVK]   VK_AMD_shader_ballot, spec version 1
[CLVK]   VK_AMD_shader_core_properties, spec version 2
[CLVK]   VK_AMD_shader_core_properties2, spec version 1
[CLVK]   VK_AMD_shader_explicit_vertex_parameter, spec version 1
[CLVK]   VK_AMD_shader_fragment_mask, spec version 1
[CLVK]   VK_AMD_shader_image_load_store_lod, spec version 1
[CLVK]   VK_AMD_shader_info, spec version 1
[CLVK]   VK_AMD_shader_trinary_minmax, spec version 1
[CLVK]   VK_AMD_texture_gather_bias_lod, spec version 1
[CLVK]   VK_GOOGLE_decorate_string, spec version 1
[CLVK]   VK_GOOGLE_hlsl_functionality1, spec version 1
[CLVK]   VK_GOOGLE_user_type, spec version 1
[CLVK] Getting Vulkan device properties
[CLVK] Unrecognized device 'Radeon RX 5500', some device properties will be incorrect.
[CLVK] Initialising driver behaviors
[CLVK]   driverName = AMD open-source driver
[CLVK]   driverInfo =
[CLVK]   conformanceVersion = 1.2.0.2
[CLVK] Driver behaviors:
[CLVK]   use_reset_command_buffer_bit = false
[CLVK] Initialising features
[CLVK] 8-bit storage: SSBO = 1, UBO = 1, Push constants = 0
[CLVK] 16-bit storage: SSBO = 1, UBO = 1, Push constants = 0
[CLVK] Device supports 2 calibrateable time domains
[CLVK]   Device
[CLVK]   Clock monotonic
[CLVK] Creating Vulkan device and queues
[CLVK] Device's resources per stage limits:
[CLVK]     total = 4294967295
[CLVK]     uniform buffers = 4294967295
[CLVK]     storage buffers = 4294967295
[CLVK] Device's max buffer size = 4.000000 GB
[CLVK] Device's max push constant size = 128.000000  B
[CLVK] Device has 8 memory types:
[CLVK]     0: heap = 0, 1.734375 GB | DEVICE_LOCAL
[CLVK]     1: heap = 1, 251.408203 GB | HOST_VISIBLE HOST_COHERENT
[CLVK]     2: heap = 2, 256.000000 MB | HOST_VISIBLE HOST_COHERENT DEVICE_LOCAL
[CLVK]     3: heap = 1, 251.408203 GB | HOST_VISIBLE HOST_COHERENT HOST_CACHED
[CLVK]     4: heap = 0, 1.734375 GB | DEVICE_LOCAL
[CLVK]     5: heap = 1, 251.408203 GB | HOST_VISIBLE HOST_COHERENT
[CLVK]     6: heap = 2, 256.000000 MB | HOST_VISIBLE HOST_COHERENT DEVICE_LOCAL
[CLVK]     7: heap = 1, 251.408203 GB | HOST_VISIBLE HOST_COHERENT HOST_CACHED
[CLVK] Device has 3 memory heaps:
[CLVK]     0: 1.734375 GB | HOST_VISIBLE DEVICE_LOCAL
[CLVK]     1: 251.408203 GB |
[CLVK]     2: 256.000000 MB | HOST_VISIBLE DEVICE_LOCAL
[CLVK] Initialised 1 devices
[CLVK] Initialisation complete
Platform: clvk
Device: Radeon RX 5500
[CLVK] Created temporary folder "clvk-D3TIN4"
[CLVK] About to run "/xxxx/clvk/build/clspv clvk-D3TIN4/source.cl  -cl-single-precision-constant  -no-8bit-storage=pushconstant  -no-16bit-storage=pushconstant  -max-pushconstant-size=128  -int8  -std430-ubo-layout  -global-offset    -o clvk-D3TIN4/compiled.spv"
[CLVK] Return code was: 0
[CLVK] Loaded SPIR-V binary from "clvk-D3TIN4/compiled.spv", size = 310 words
[CLVK] check_capabilities: Program requires SPIR-V capability 1.
[CLVK] created pipeline 0x55e1d29573f0 for kernel test_simple
[CLVK] flush: queue = 0x55e1d2959ea0, event = 0x7ffc6b54fa48
[CLVK] executing batch of 1 kernels
[CLVK] flush: queue = 0x55e1d2959ea0, event = (nil)
Failed comparison at buffer_data[1]: expected 1 but got 0
.....
Failed comparison at buffer_data[254]: expected 254 but got 0
Failed comparison at buffer_data[255]: expected 255 but got 0
[CLVK] flush: queue = 0x55e1d2959ea0, event = 0x7ffc6b54fa48
[CLVK] flush: queue = 0x55e1d2959ea0, event = (nil)
[CLVK] destroying pipeline 0x55e1d29573f0 for kernel test_simple
Test failed.

**Comment by tingxingdong** [comment]
LOG=4. Is that because the host pointer is NULL ?

==================

[CLVK] clCreateCommandQueue: context = 0x561da9f908e0, device = 0x561da9d3c128, properties = 0, errcode_ret = 0x7ffe80b24df4
[CLVK] retain: obj = 0x561da9f908d0, refcount now 4
[CLVK] clCreateBuffer: context = 0x561da9f908e0, flags = 18, size = 1024, **host_ptr = (nil),** errcode_ret = 0x7ffe80b24df4
[CLVK] retain: obj = 0x561da9f908d0, refcount now 5
[CLVK] memory_type_index_for_resource: outer returning 3

**Comment by kpet** [comment]
Hmm, this is odd. This could be a Vulkan driver bug but given how simple this test is, it seems unlikely. The interface between clvk and clspv changed recently so I'm wondering if this couldn't be a descriptor issue. Have you tried a clean build?

**Comment by tingxingdong** [comment]
Yes. I git clone a fresh one on Linux.

**Comment by tingxingdong** [comment]
it might due to an internal bug. SO close it
