### ISSUE TITLE
Split uniform regions into multiple compute dispatches when device limits are exceeded

### ISSUE THREAD

**Issue by kpet** [kpet/clvk#266]
Some devices only support a small number of work groups.

**Comment by rjodinchr** [comment]
I could use this feature.

I have a concern with it about atomic operations and global barriers.
But I guess that uniform regions means regions without any of those?

**Comment by kpet** [comment]
Global barriers don't exist in OpenCL and the standard doesn't specify concurrency requirements for work-item execution. It is valid to execute work-items one after the other in the absence of barriers. As long as we never split work-groups, splitting bigger NDRanges into many separate compute dispatches when necessary can be considered an implementation detail.

**Comment by kpet** [comment]
Go for it, it should be rather straightforward. You should be able to reuse the existing region offset mechanism. If not, let me know and let's discuss alternatives.

**Comment by rjodinchr** [comment]
I have something that seems to be working.
I am not thinking about how to integrate a test.
To develop I just override the vklimits to have them small enough to be able to iterate quickly and make sure I am looking at the corner case.
But for the CI, changing the vklimits seems complicated.
Do you have an idea for that?

**Comment by rjodinchr** [comment]
@kpet ?

**Comment by kpet** [comment]
I can't think of an easy and non-intrusive way of testing this. A few options that come to mind:
- Add testing functions to clvk that the test suite could call to restrict the limits
- Add an environment variable interface to restrict those limits
- Use a Vulkan layer to restrict the limits
