### ISSUE TITLE
clinfo clGetExtensionFunctionAddress error

### ISSUE THREAD

**Issue by SirRujak** [kpet/clvk#27]
When running the Solus repository version of opencl it returns the following error:

`clinfo: ./build/libOpenCL.so.1: no version information available (required by clinfo)
clinfo: relocation error: clinfo: symbol clGetExtensionFunctionAddress version OPENCL_1.0 not defined in file libOpenCL.so.1 with link time reference
`

Also tried running the PlaidML library at git commit https://github.com/plaidml/plaidml/commit/86961565169b693066fb2c91fe246c52ddde1a96 but was as expected informed that no OpenCL devices were found. Sadly I'm not terribly experienced with OpenCL in general so I don't have much other information. If there is anything else I can try I would like to help in any way I can!

Setup:
OS: Solus
Kernel: 4.18.9
Vulkan: 1.1.82.0
LLVM: 6.0.1
clinfo: 2.2.18.04.06

**Comment by SirRujak** [comment]
Thank you for the instructions!
I rebuilt it with the fix and it indeed did fix the clinfo issue. I got the following output for clinfo:

`LD_LIBRARY_PATH=./build clinfo
clinfo: ./build/libOpenCL.so.1: no version information available (required by clinfo)
Xlib:  extension "NV-GLX" missing on display ":0".
Number of platforms                               1
  Platform Name                                   clvk
  Platform Vendor                                 clvk
  Platform Version                                OpenCL 1.2 clvk
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             

  Platform Name                                   clvk
Number of devices                                 1
  Device Name                                     AMD RADV POLARIS10 (LLVM 6.0.1)
  Device Vendor                                   FIXME
  Device Vendor ID                                0x1002
  Device Version                                  OpenCL 1.2 Vulkan v1.1.70 driver 75501574
  Driver Version                                  1.2 Vulkan v1.1.70 driver 75501574
  Device OpenCL C Version                         OpenCL C 1.2 Vulkan v1.1.70 driver 75501574
  Device Type                                     GPU
  Device Profile                                  FULL_PROFILE
  Device Available                                Yes
  Compiler Available                              Yes
  Linker Available                                Yes
  Max compute units                               1
  Max clock frequency                             0MHz
  Device Partition                                (core)
    Max number of sub-devices                     0
    Supported partition types                     None
    Supported affinity domains                    (n/a)
  Max work item dimensions                        3
  Max work item sizes                             2048x2048x2048
  Max work group size                             2048
  Preferred work group size multiple              4
  Preferred / native vector sizes                 
    char                                                 1 / 1       
    short                                                1 / 1       
    int                                                  1 / 1       
    long                                                 1 / 1       
    half                                                 1 / 1        (n/a)
    float                                                1 / 1       
    double                                               1 / 1        (n/a)
  Half-precision Floating-point support           (n/a)
  Single-precision Floating-point support         (core)
    Denormals                                     No
    Infinity and NANs                             Yes
    Round to nearest                              Yes
    Round to zero                                 No
    Round to infinity                             No
    IEEE754-2008 fused multiply-add               No
    Support is emulated in software               No
    Correctly-rounded divide and sqrt operations  No
  Double-precision Floating-point support         (n/a)
  Address bits                                    32, Little-Endian
  Global memory size                              8589934592 (8GiB)
  Error Correction support                        No
  Max memory allocation                           4294967295 (4GiB)
  Unified memory for Host and Device              No
  Minimum alignment for any data type             128 bytes
  Alignment of base address                       1024 bits (128 bytes)
  Global Memory cache type                        None
  Image support                                   No
  Local memory type                               Local
  Local memory size                               32768 (32KiB)
  Max number of constant args                     8
  Max constant buffer size                        65536 (64KiB)
  Max size of kernel argument                     1024
  Queue properties                                
    Out-of-order execution                        No
    Profiling                                     Yes
  Prefer user sync for interop                    Yes
  Profiling timer resolution                      40ns
  Execution capabilities                          
    Run OpenCL kernels                            Yes
    Run native kernels                            No
  printf() buffer size                            1048576 (1024KiB)
  Built-in kernels                                cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store
  Device Extensions                               cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_byte_addressable_store

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  clvk
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   Success [P0]
  clCreateContext(NULL, ...) [default]            Success [P0]
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  Success (1)
    Platform Name                                 clvk
    Device Name                                   AMD RADV POLARIS10 (LLVM 6.0.1)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  Success (1)
    Platform Name                                 clvk
    Device Name                                   AMD RADV POLARIS10 (LLVM 6.0.1)
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  Success (1)
    Platform Name                                 clvk
    Device Name                                   AMD RADV POLARIS10 (LLVM 6.0.1)
`
Running LD_LIBRARY_PATH=./build CVK_LOG=4 plaidml-setup did not give any extra information compared to running it without so I am now guessing that it is on their end rather than an issue with clvk. We can either keep this issue open or close it however you like! If I get plaidml to recognize it I'll make sure to add it as a comment on your issue for tracking working applications.

**Comment by kpet** [comment]
Glad to see it's worked for you!

>plaidml-setup did not give any extra information compared to running it without so I am now guessing that it is on their end

I haven't had much success getting to that point on my side. I did manage to make it build but it seems to be missing dependencies at execution time.

>We can either keep this issue open or close it however you like!

I'd rather we close this one (`clGetExtensionFunctionAddress` now present) and track the separate PlaidML issue under a separate issue (feel free to create it as soon as you have evidence of a problem with clvk).

>If I get plaidml to recognize it I'll make sure to add it as a comment on your issue for tracking working applications.

Great, thank you and good luck :).
