### ISSUE TITLE
Support for clCreateImage?

### ISSUE THREAD

**Issue by abrarmatin** [kpet/clvk#271]
When running CLVK, getting error code -59 (INAVLID_OPERATION) on clCreateImage. Seems like the context doesn't support images: "CL_INVALID_OPERATION: if there are no devices in context that support images".

Does the latest version of clvk have support for clCreateImage? If not, are there plans to add this anytime soon?

**Comment by kpet** [comment]
Images are partially supported but creating an image from a buffer (https://github.com/kpet/clvk/issues/43) or with a host pointer (https://github.com/kpet/clvk/issues/121) for example is not supported yet.
