### ISSUE TITLE
clCreateImage returns -5 CL_OUT_OF_RESOURCES	

### ISSUE THREAD

**Issue by LukeFernandes** [kpet/clvk#303]
clCreateImage returns -5 (CL_OUT_OF_RESOURCES) using clvk.

The following (a fairly standard bit of setup) works on the Intel and Nvidia implementations:

cl_image_format luminance_image_format = cl_image_format{CL_LUMINANCE, CL_FLOAT};
cl_image_desc this_image_type = cl_image_desc{CL_MEM_OBJECT_IMAGE2D, (size_t)W, (size_t)H, 1, 1, NULL, 0, 0, NULL};
input_image = clCreateImage(context, CL_MEM_READ_WRITE, &luminance_image_format, &this_image_type, NULL, &error_code);

I don't think this is related to lack of read-write image support as that usually refers to support for read-write declarations in the kernel (which is supported in OpenCL 2.0 and 3.0) not to read-write tagging on the host side (which works on OpenCL 1.2). Also, making it CL_MEM_READ_ONLY does not fix the problem.

**Comment by kpet** [comment]
It seems the application assumes that `{CL_LUMINANCE, CL_FLOAT}` is supported but this format is not part of the minimum required formats. The application should check the format is supported via `clGetSupportedImageFormats` before using it.

Having said that, it doesn't look too hard to add support for CL_LUMINANCE to clvk. I'll do that.

**Comment by kpet** [comment]
@LukeFernandes  I've added partial support with #305. Depending on what your application does, it may be enough or you may also need #304. Note that #305 will allow some kernel-side access but only the first component will be correct when reading from a CL_LUMINANCE image. Feel free to let me know how it goes.

**Comment by LukeFernandes** [comment]
Thanks for this! I wasn't aware CL_LUMINANCE was an optional part of the spec, I'll add clGetSupportedImageFormats as good practice. 

As the first three components are all the same as each other with other implementations, I don't see how just using #305 would be a problem (as I would just use .x, i.e. the first component). I will test and get back to you...
