### ISSUE TITLE
Fully support kernel-side access to CL_LUMINANCE images

### ISSUE THREAD

**Issue by kpet** [kpet/clvk#304]
CL_LUMINANCE is currently implemented as CL_R which means only the first component will be correct.
It seems Vulkan doesn't support this out-of-the-box. It could be done by detecting a luminance format is used from within the kernels to duplicate components appropriately.

**Comment by jrprice** [comment]
I suspect you can probably also do this via `VkComponentMapping` to automatically swizzle as `.rrra`.

**Comment by kpet** [comment]
Yup, didn't think of this when I first looked at supporting CL_LUMINANCE but it's _the_ obvious way of doing it. Feel free to propose a PR if you're interested.
