### ISSUE TITLE
Option `-max-ubo-size` exceeds limit of clspv on certain vulkan devices when compiling kernel

### ISSUE THREAD

**Issue by fxzjshm** [kpet/clvk#318]
In [this line of program.cpp](https://github.com/kpet/clvk/blob/1d0e3864a9f28ad17ed709e54b9eabf973529dc0/src/program.cpp#L719), `max-ubo-size` is assigned `maxUniformBufferRange` defined in [VkPhysicalDeviceLimits](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkPhysicalDeviceLimits.html) which has a `uint32_t` type;
however, `max-ubo-size` itself is a `llvm::cl::opt<int>` defined in [clspv/Option.cpp](https://github.com/google/clspv/blob/3f772c0a122050903e3bb3a4445bc1f74bc30a7a/lib/Option.cpp#L125).

Although this should't matter in normal cases, on certain devices (e.g. a Vega 7 of AMD R7-4800H) it has (output of `vulkaninfo`, tested both on mesa and amdvlk driver):
```
	maxUniformBufferRange                           = 4294967295
```
this then causes `clspv` to complain when compiling kernel:
```
[CLVK] About to run "/opt/clvk/clspv clvk-pmGZhr/source.cl -cl-single-precision-constant  -fp64=0  -int8  -std430-ubo-layout  -spv-version=1.5  -max-pushconstant-size=128  -max-ubo-size=4294967295  -global-offset  -long-vector  -module-constants-in-storage-buffer    -o clvk-pmGZhr/compiled.spv"
clspv: for the --max-ubo-size option: '4294967295' value invalid for integer argument!
[CLVK] Return code was: 256
[CLVK] compile_source: failed to compile the program
```

So ...
* should the value be checked in program.cpp, e.g. `options +=  " -max-ubo-size=" + std::to_string(std::min(device->vulkan_max_uniform_buffer_range(), std::numeric_limits<int>::max())) + " "; ` (or more generically, use some magic to get the template parameter `int` of `llvm::cl::opt<int> maximum_ubo_size` ) ?
* or open an issue in clspv and suggest that maybe `llvm::cl::opt<uint32_t>` might be used?
* or ... some better solution?

PS: the same thing applies to `-max-pushconstant-size` and `maxPushConstantsSize`

**Comment by kpet** [comment]
Thanks for the report! I think the best solution is to change clspv, I've created https://github.com/google/clspv/pull/756.

**Comment by fxzjshm** [comment]
Thank you for this!
