### ISSUE TITLE
[SWIFTSHADER] building from clvk root cmake is broken

### ISSUE THREAD

**Issue by rjodinchr** [kpet/clvk#357]
Trying to build swiftshader from `clvk` cmake does not work anymore.
It seems that swiftshader is trying to use a mix of LLVM from its own third_party dependencies and the one for `clvk`.
But there are not at the same version (10 vs ToT), which make swiftshader build fail.

Workaound: build swiftshader on its own as it is done in azur

**Comment by kpet** [comment]
@rjodinchr With https://github.com/kpet/clvk/pull/493 and `aae98adc2222dcada4aa952cccad48ab08e34004` for Switfshader, it seems to just work for me. Have upstream LLVM/Swiftshader fixed the issue already?

**Comment by rjodinchr** [comment]
I  confirm, it is fixed
