### ISSUE TITLE
CL_LUMINANCE and CL_INTENSITY image formats

### ISSUE THREAD

**Issue by alan-baker** [kpet/clvk#384]
I notice clvk maps the these formats to single channel Vulkan formats such as VK_FORMAT_R32_SFLOAT. E.g.
```
        {{CL_LUMINANCE, CL_FLOAT}, VK_FORMAT_R32_SFLOAT},
```

The OpenCL spec says that the results for these formats the single channel value should be replicated in each channel, but the Vulkan formats are pure single channel formats. This results in mismatches in CTS due to the lack of replication, such as:
```
[CL_INTENSITY CL_FLOAT                 1] - CL_FILTER_NEAREST - CL_ADDRESS_NONE - UNNORMALIZED
FAILED norm_offsets: 0:
ERROR: TEST FAILED: Read is erroneously clamping coordinates for image size 652!
Sample 0: coord {0.000000(0x0p+0)} did not validate!
	Expected (-1.27092e-24,-1.27092e-24,-1.27092e-24,-1.27092e-24),
	got      (-1.27092e-24,0,0,1),
	error of 0
Step by step:
Starting coordinate: 0.000000	Reference integer coords calculated: { 0, 0 }
	ulps: 0.00, 12888623.00, 12888623.00, 10141204801825835211973625643008.00  (max allowed: 2.00)

FAILED: [CL_INTENSITY CL_FLOAT                 1] - CL_FILTER_NEAREST - CL_ADDRESS_NONE - UNNORMALIZED

[CL_LUMINANCE CL_FLOAT                 1] - CL_FILTER_NEAREST - CL_ADDRESS_NONE - UNNORMALIZED
FAILED norm_offsets: 0:
ERROR: TEST FAILED: Read is erroneously clamping coordinates for image size 652!
Sample 0: coord {0.000000(0x0p+0)} did not validate!
	Expected (-1.27092e-24,-1.27092e-24,-1.27092e-24,1),
	got      (-1.27092e-24,0,0,1),
	error of 0
Step by step:
Starting coordinate: 0.000000	Reference integer coords calculated: { 0, 0 }
	ulps: 0.00, 12888623.00, 12888623.00, 0.00  (max allowed: 2.00)

FAILED: [CL_LUMINANCE CL_FLOAT                 1] - CL_FILTER_NEAREST - CL_ADDRESS_NONE - UNNORMALIZED
```

Probably these formats should not be supported for now.

**Comment by kpet** [comment]
Hmm, this was added not too long ago and there is code to handle the replication: https://github.com/kpet/clvk/blob/main/src/api.cpp#L4339. I remember running the CTS to check these were working correctly but maybe I missed a case.

**Comment by alan-baker** [comment]
Ok, I wonder if this is a driver issue with read_write images. I believe those are the only variants that failed on closer inspection.

**Comment by kpet** [comment]
Oh, I think I know what happened then. I recently switched clvk to OpenCL 3.0 and enabled support for read write images but did not run a full sweep of image streams (just a quick subset) so probably did not hit those combinations that most likely never passed.

**Comment by kpet** [comment]
I can reproduce the failure at my end (NVidia 1050 Ti, 515.48.07 Linux 64-bit). It seems to affect reads using integer coordinates on either read-only or read-write images. I'm pretty sure all tests on read-only images used to pass so we might be looking at a regression. Have those tests started to fail recently for you or are you digging into failures that have always been there?

**Comment by kpet** [comment]
The validation layers are flagging an invalid use of swizzles:

```
[CLVK] Validation Error: [ VUID-VkWriteDescriptorSet-descriptorType-00336 ] Object 0: handle = 0x9fde6b0000000014, type = VK_OBJECT_TYPE_DESCRIPTOR_SET; | MessageID = 0xc258ecf8 | vkUpdateDescriptorSets() pDescriptorWrites[0] failed write update validation for VkDescriptorSet 0x9fde6b0000000014[] with error: Write update to VkDescriptorSet 0x9fde6b0000000014[] allocated with VkDescriptorSetLayout 0xe7f79a0000000005[] binding #0 failed with error message: Attempted write update to image descriptor failed due to: ImageView (VkImageView 0xcfef35000000000a[]) has a non-identiy swizzle component,  r swizzle = VK_COMPONENT_SWIZZLE_R, g swizzle = VK_COMPONENT_SWIZZLE_R, b swizzle = VK_COMPONENT_SWIZZLE_R, a swizzle = VK_COMPONENT_SWIZZLE_R.. The Vulkan spec states: If descriptorType is VK_DESCRIPTOR_TYPE_STORAGE_IMAGE or VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT, the imageView member of each element of pImageInfo must have been created with the identity swizzle (https://www.khronos.org/registry/vulkan/specs/1.3-extensions/html/vkspec.html#VUID-VkWriteDescriptorSet-descriptorType-00336)
```

We can't use the swizzles with storage images which probably means we can't support the formats cleanly without additional work.

**Comment by alan-baker** [comment]
That makes sense. The test previously skipped read_write images as a 1.2 implementation. Clspv translates all read_only images as sampled where the swizzling work.

**Comment by kpet** [comment]
I think you missed part of my comment: I'm also seeing failures on read-only images with integer coordinates where clspv seems to be using storage images. If we can get clspv to use sampled images (and stop reporting CL_LUMINANCE and CL_INTENSITY formats for read-write images in clvk) then we can support the formats for read-only and write-only images. If we have to use storage images for read-only images with integer coordinates in clspv for whatever reason (haven't dived into the details), then we can't support the formats for read-only images. Does that make sense?

Support was originally contributed by someone with the need for those formats so I'm keep we try hard to not break their use-case if we can reasonably avoid it.

**Comment by alan-baker** [comment]
> I think you missed part of my comment: I'm also seeing failures on read-only images with integer coordinates where clspv seems to be using storage images. If we can get clspv to use sampled images (and stop reporting CL_LUMINANCE and CL_INTENSITY formats for read-write images in clvk) then we can support the formats for read-only and write-only images. 

At this point I believe clspv always generates read_only images as sampled images. The last gap was 1d buffer images. If you're still seeing this I'd consider it a bug in clspv that definitely needs addressed.

I think write_only have to be generated as storage images so maybe those need omitted, but I'd have to look into the full restrictions in Vulkan more fully.

**Comment by kpet** [comment]
Ok, I'll double-check and raise a clspv bug with the specific case then.

write_only images have to use storage images but all CTS tests seem to be passing. clvk is using an invalid set of swizzles but we don't need them. I think it's possible to change the swizzles and pass the CTS.

For read-write, I'll stop reporting the formats. We absolutely need storage images there and we can't support the read part without inserting ugly format-dependant component replication code. It's doable but I suggest we don't go there until someone comes up with a strong use-case.
