### ISSUE TITLE
[CI] simple_test: UNSUPPORTED: pCreateInfo->pNext 

### ISSUE THREAD

**Issue by rjodinchr** [kpet/clvk#441]
https://github.com/kpet/clvk/commit/a55be50a0e8f5a2ea855d8832c7989cb385f246b introduces this error message when executing `simple_test` over swiftshader in the CI:
```
/home/runner/work/clvk/clvk/swiftshader/src/Vulkan/libVulkan.cpp:1094 WARNING: UNSUPPORTED: pCreateInfo->pNext sType = 1000177000
/home/runner/work/clvk/clvk/swiftshader/src/Vulkan/libVulkan.cpp:1094 WARNING: UNSUPPORTED: pCreateInfo->pNext sType = 1000082000
```
https://github.com/kpet/clvk/actions/runs/3257323026/jobs/5348521433#step:23:648

**Comment by kpet** [comment]
Swiftshader reports a version of Vulkan it doesn't fully supports it would appear. This is definitely wrong but maybe we can tweak the logic in clvk to help. Are the warnings the only symptoms you're seeing?

**Comment by rjodinchr** [comment]
It blocks google infra, as those warnings are considered as errors there.
But yes, it is the only symptom I have seen.

**Comment by rjodinchr** [comment]
https://swiftshader-review.googlesource.com/c/SwiftShader/+/69328

**Comment by kpet** [comment]
Thanks for that, I'm kicking off another build.

**Comment by kpet** [comment]
The new build has succeeded, closing.
