### ISSUE TITLE
OpenCL CTS api:kernel_arg_info conformance test failed

### ISSUE THREAD

**Issue by book912** [kpet/clvk#450]
Hi, I ported clvk on android and ran OpenCL CTS.  When I run api:kernel_arg_info conformance test, the result is failed. The error information is related to "clBuildProgram failed".
But I noticed that this test can pass here https://github.com/kpet/clvk/issues/51
I clone the latest clvk code, and did not modify any clvk or clspv code, do you know why the test failed?

**Comment by rjodinchr** [comment]
I am not sure why it has been flagged as passed. But to me it is failing.
The error message for some kernels in it is:
```
pointer-to-void is only supported with int8 support and opaque pointers
```
Which means that it is depending on:
https://github.com/google/clspv/issues/826
On which @callumfare is working on I believe.

**Comment by kpet** [comment]
The test is passing for me but with the following restrictions:

```
diff --git a/test_conformance/api/test_kernel_arg_info.cpp b/test_conformance/api/test_kernel_arg_info.cpp
index d0681dfd..7342f3ab 100644
--- a/test_conformance/api/test_kernel_arg_info.cpp
+++ b/test_conformance/api/test_kernel_arg_info.cpp
@@ -34,7 +34,7 @@ static const std::vector<cl_kernel_arg_address_qualifier> address_qualifiers = {
 
 static const std::vector<std::string> image_arguments = {
     "image2d_t", "image3d_t",        "image2d_array_t",
-    "image1d_t", "image1d_buffer_t", "image1d_array_t"
+    "image1d_t", /*"image1d_buffer_t",*/ "image1d_array_t"
 };
 
 static const std::vector<cl_kernel_arg_access_qualifier> access_qualifiers = {
@@ -440,7 +440,7 @@ generate_all_type_arguments(cl_device_id deviceID)
 {
     std::vector<std::string> ret = {
         "char",           "short",        "int",           "float",
-        "void",           "uchar",        "unsigned char", "ushort",
+        /*"void",*/           "uchar",        "unsigned char", "ushort",
         "unsigned short", "uint",         "unsigned int",  "char unsigned",
         "short unsigned", "int unsigned", "signed short",  "signed int",
         "signed long",    "short signed", "int signed",    "signed",
```
It is not expected to pass unmodified. As @rjodinchr said, physical pointers and IIRC https://github.com/kpet/clvk/issues/122 will be required to fully and cleanly pass this test. Both are in progress.

**Comment by book912** [comment]
I already understand. Thank you for your answers
