### ISSUE TITLE
FR: Forcing FP16 support

### ISSUE THREAD

**Issue by stolk** [kpet/clvk#542]
It would be nice if there was a way to force FP16 support.

When compiling a kernel that uses the fp16 extension, I see this:
```
[CLVK] About to run "/home/bram/src/clvk/build/clspv clvk-AcBj6h/source.cl  -cl-single-precision-constant  -cl-kernel-arg-info   -fp16=0  -fp64=0  -int8=0  -std430-ubo-layout  -decorate-nonuniform    -arch=spir  -spv-version=1.5  -max-pushconstant-size=128  -max-ubo-size=1073741824  -global-offset  -long-vector  -module-constants-in-storage-buffer  -cl-arm-non-uniform-work-group-size     -o clvk-AcBj6h/compiled.spv"
[CLVK] Return code was: 65280
```

If I run that command manually, I indeed see the compile fail, due to fp16 not being supported.

If I run that command slightly modified with `-fp16=1` then the compile succeeds, and I get a `compiled.spv` output.

This means that somewhere along the stack, OpenCL thinks it cannot do fp16, whereas it seems that it can. Caveat: I have not actually ran the spirv output yet, on the GPU. 

Using vulkaninfo is see no Float16 support.

Using clinfo is see no fp16 extension.

Also: what does the `-256` return value for clspv signify?

[vi.log](https://github.com/kpet/clvk/files/11638159/vi.log)
[cli.log](https://github.com/kpet/clvk/files/11638160/cli.log)

Platform: rPi-400

OS: Ubuntu 23.04

**Comment by stolk** [comment]
Never mind, I think I need to close this.

I think the GPU somehow really does not do fp16 and int8 based on this:
```
[CLVK] SPIR-V offset 28: SPIR-V WARNING:
    Unsupported SPIR-V capability: SpvCapabilityFloat16 (9)
    28 bytes into the SPIR-V binary
[CLVK] SPIR-V offset 36: SPIR-V WARNING:
    Unsupported SPIR-V capability: SpvCapabilityInt8 (39)
    36 bytes into the SPIR-V binary
[CLVK] SPIR-V offset 60: SPIR-V WARNING:
    Unsupported SPIR-V capability: SpvCapabilityShaderNonUniform (5301)
    60 bytes into the SPIR-V binary
unknown NIR ALU inst: vec1 16 div ssa_202 = b2f16! ssa_175
```

**Comment by stolk** [comment]
One last note: ignoring the lack of FP16 support in the report does work on AMD.

I've found that the AMD driver is capable of compiling and executing FP16 instructions despite both OpenCL and Vulkan claiming there is no support for it. (Tested on AMD RX580 and `libvulkan_radeon.so` on Ubuntu 23.04.)

**Comment by kpet** [comment]
>Also: what does the -256 return value for clspv signify?

Anything non-zero means failure.

Were you trying to run an application with a hard requirement on FP16? We could add support to provide (some) FP16 support using FP32 to deal with this. It's not the first time that the idea comes up so I've created https://github.com/kpet/clvk/issues/545.
