### ISSUE TITLE
Improve descriptor set reuse

### ISSUE THREAD

**Issue by kpet** [kpet/clvk#580]
We currently allocate new descriptor sets for each kernel enqueue when kernel arguments change but we don't use features such as update after bind so we only really need one set of descriptor sets per concurrent instance of the kernel command building code. With the current approach to command queue locks, that should mean one per kernel per command queue.

**Comment by rjodinchr** [comment]
I'll look into it in the coming days

**Comment by rjodinchr** [comment]
Should we close this issue?
