### ISSUE TITLE
Fix issues with printf tests.

### ISSUE THREAD

**Issue by Rekt3421** [kpet/clvk#714]
Right now the majority of conformance tests for printf related to strings are failing, there are about 11 tests and 10 fail. It mostly has to do with how we process the strings in printf.cpp and also how kernel descriptors are setup here is an example of issues related to printf.cpp

```
1)testing printf("%s","")
terminate called after throwing an instance of 'std::out_of_range'
```

and here is an example of issues to due to kernel descriptors not setup properly 
```
12)testing printf("%s","foo\0foo")
No data read from analysis buffer
verifyOutputBuffer failed with kernel: 
__kernel void test9(void)
{
   printf("%s\n","foo\0foo");
}

 expected: foo
 got:     
```

**Comment by rjodinchr** [comment]
This issue can be closed
